// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post.proto

/*
Package post is a generated protocol buffer package.

It is generated from these files:
	post.proto

It has these top-level messages:
	SearchParams
	Post
*/
package post

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchParams struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *SearchParams) Reset()                    { *m = SearchParams{} }
func (m *SearchParams) String() string            { return proto.CompactTextString(m) }
func (*SearchParams) ProtoMessage()               {}
func (*SearchParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SearchParams) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Post struct {
	Id          int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	CreatedAt   string `protobuf:"bytes,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt   string `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Post) Reset()                    { *m = Post{} }
func (m *Post) String() string            { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()               {}
func (*Post) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Post) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Post) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Post) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchParams)(nil), "post.SearchParams")
	proto.RegisterType((*Post)(nil), "post.Post")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Posts service

type PostsClient interface {
	Get(ctx context.Context, in *SearchParams, opts ...grpc.CallOption) (*Post, error)
}

type postsClient struct {
	cc *grpc.ClientConn
}

func NewPostsClient(cc *grpc.ClientConn) PostsClient {
	return &postsClient{cc}
}

func (c *postsClient) Get(ctx context.Context, in *SearchParams, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := grpc.Invoke(ctx, "/post.Posts/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Posts service

type PostsServer interface {
	Get(context.Context, *SearchParams) (*Post, error)
}

func RegisterPostsServer(s *grpc.Server, srv PostsServer) {
	s.RegisterService(&_Posts_serviceDesc, srv)
}

func _Posts_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.Posts/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServer).Get(ctx, req.(*SearchParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Posts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "post.Posts",
	HandlerType: (*PostsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Posts_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post.proto",
}

func init() { proto.RegisterFile("post.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x41, 0x8a, 0xc2, 0x30,
	0x14, 0x86, 0x27, 0x6d, 0x33, 0xd0, 0x37, 0xc3, 0x2c, 0x1e, 0xb3, 0x08, 0x03, 0x23, 0xa5, 0x1b,
	0xbb, 0x2a, 0xa2, 0x27, 0xe8, 0xca, 0x6d, 0xa9, 0x07, 0x90, 0xd8, 0x04, 0x0c, 0xa8, 0x09, 0xc9,
	0xf3, 0x16, 0x1e, 0x5a, 0x92, 0x56, 0x28, 0xee, 0x92, 0xef, 0xfb, 0x17, 0xef, 0x03, 0x70, 0x36,
	0x50, 0xeb, 0xbc, 0x25, 0x8b, 0x45, 0x7c, 0xd7, 0x2b, 0xf8, 0x3e, 0x68, 0xe9, 0xc7, 0x73, 0x2f,
	0xbd, 0xbc, 0x06, 0xfc, 0x81, 0xcc, 0x28, 0xc1, 0x2a, 0xd6, 0xf0, 0x21, 0x33, 0xaa, 0x7e, 0x30,
	0x28, 0x7a, 0x1b, 0xe8, 0x5d, 0xe0, 0x2f, 0x70, 0x32, 0x74, 0xd1, 0x22, 0xab, 0x58, 0x53, 0x0e,
	0xd3, 0x07, 0x2b, 0xf8, 0x52, 0x3a, 0x8c, 0xde, 0x38, 0x32, 0xf6, 0x26, 0xf2, 0xe4, 0x96, 0x08,
	0xff, 0x01, 0x46, 0xaf, 0x25, 0x69, 0x75, 0x94, 0x24, 0x8a, 0x34, 0x28, 0x67, 0xd2, 0x51, 0xd4,
	0x77, 0xa7, 0x5e, 0x9a, 0x4f, 0x7a, 0x26, 0x1d, 0x6d, 0x37, 0xc0, 0xe3, 0x35, 0x01, 0xd7, 0x90,
	0xef, 0x35, 0x21, 0xb6, 0xa9, 0x68, 0x99, 0xf0, 0x07, 0x13, 0x8b, 0xbb, 0xfa, 0xe3, 0xf4, 0x99,
	0x6a, 0x77, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93, 0xaf, 0xea, 0x9f, 0xfb, 0x00, 0x00, 0x00,
}
