# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "post.SearchParams" do
    optional :id, :int32, 1
  end
  add_message "post.Post" do
    optional :id, :int32, 1
    optional :title, :string, 2
    optional :description, :string, 3
    optional :created_at, :string, 4
    optional :updated_at, :string, 5
  end
end

module Post
  SearchParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("post.SearchParams").msgclass
  Post = Google::Protobuf::DescriptorPool.generated_pool.lookup("post.Post").msgclass
end
